### ISSUE TITLE
20230112 Not Working....

### ISSUE THREAD

**Issue by pjpreilly** [blueboxd/chromium-updater#3]
I tried to GET  Canary 1092007.... the status just says "Updating..." nothing in the Console messages....
never gets the file.....

**Comment by pjpreilly** [comment]
1/12/23 4:58:09.177 PM Chromium Updater: canary:{
    canary = 1;
    revision = 1092007;
    url = "https://github.com/blueboxd/chromium-legacy/releases/download/1092007/1092007.tar.xz";
    version = "111.0.5536.0";
}, stable:{
    canary = 0;
    revision = 1241;
    url = "https://github.com/blueboxd/chromium-legacy/releases/download/stable/109.0.5414.87.1.tar.xz";
    version = "109.0.5414.87.1";
}

**Comment by pjpreilly** [comment]
...  & the get info has the same version as well as date created/modified for all the releases which is confusing....
![2023-01-12 06 43 58 pm](https://user-images.githubusercontent.com/10430084/212204802-092b2087-5474-4a3c-ae22-70158fd7983d.png)

**Comment by blueboxd** [comment]
Fixed, please try 20230113.

**Comment by pjpreilly** [comment]
Works... Version is updated .....Dates...not so much..

**Comment by pjpreilly** [comment]
![2023-01-12 09 14 01 pm](https://user-images.githubusercontent.com/10430084/212221505-adeb35a6-2100-41e2-b78d-f5a2f27e6021.png)

**Comment by pjpreilly** [comment]
Nice response... Keep up the fight!
